export const authConsts = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FALIURE: 'LOGIN_FALIURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED'
}

export const userConsts = {
    USER_REGISTRATION_REQUEST: 'USER_REGISTRATION_REQUEST',
    USER_REGISTRATION_SUCCESS: 'USER_REGISTRATION_SUCCESS',
    USER_REGISTRATION_FALIURE: 'USER_REGISTRATION_FALIURE'
}

export const catConsts = {
    CATEGORY_FETCH_REQUEST: 'CATEGORY_FETCH_REQUEST',
    CATEGORY_FETCH_SUCCESS: 'CATEGORY_FETCH_SUCCESS',
    CATEGORY_FETCH_FAILED: 'CATEGORY_FETCH_FAILED',
    CATEGORY_CREATE_REQUEST: 'CATEGORY_CREATE_REQUEST',
    CATEGORY_CREATE_SUCCESS: 'CATEGORY_CREATE_SUCCESS',
    CATEGORY_CREATE_FAILED: 'CATEGORY_CREATE_FAILED',
    CATEGORY_UPDATE_REQUEST: 'CATEGORY_UPDATE_REQUEST',
    CATEGORY_UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
    CATEGORY_UPDATE_FAILED: 'CATEGORY_UPDATE_FAILED',
    CATEGORY_DELETE_REQUEST: 'CATEGORY_DELETE_REQUEST',
    CATEGORY_DELETE_SUCCESS: 'CATEGORY_DELETE_SUCCESS',
    CATEGORY_DELETE_FAILED: 'CATEGORY_DELETE_FAILED',
    CATEGORY_IMG_UPDATE_REQUEST: 'CATEGORY_IMG_UPDATE_REQUEST',
    CATEGORY_IMG_UPDATE_SUCCESS: 'CATEGORY_IMG_UPDATE_SUCCESS',
    CATEGORY_IMG_UPDATE_FAILED: 'CATEGORY_IMG_UPDATE_FAILED'
}

export const productConsts = {
    PRODUCT_ADD_SUCCESS: 'PRODUCT_ADD_SUCCESS',
    PRODUCT_ADD_REQUEST: 'PRODUCT_ADD_REQUEST',
    PRODUCT_ADD_FAILED: 'PRODUCT_ADD_SUCCESS',
    PRODUCT_FETCH_REQUEST: 'PRODUCT_FETCH_REQUEST',
    PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS',
    PRODUCT_FETCH_FAILED: 'PRODUCT_FETCH_FAILED',
    PRODUCT_UPDATE_REQUEST: "PRODUCT_UPDATE_REQUEST",
    PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",
    PRODUCT_UPDATE_FAILED: "PRODUCT_UPDATE_FAILED"
}

export const initDataConsts = {
    INIT_DATA_FETCH_REQUEST: 'INIT_DATA_FETCH_REQUEST',
    INIT_DATA_FETCH_SUCCESS: 'INIT_DATA_FETCH_SUCCESS',
    INIT_DATA_FETCH_FAILED: 'INIT_DATA_FETCH_FAILED'
}

export const orderConstants = {
    GET_CUSTOMER_ORDER_REQUEST: "GET_CUSTOMER_ORDER_REQUEST",
    GET_CUSTOMER_ORDER_SUCCESS: "GET_CUSTOMER_ORDER_SUCCESS",
    GET_CUSTOMER_ORDER_FAILURE: "GET_CUSTOMER_ORDER_FAILURE",

    UPDATE_CUSTOMER_ORDER_REQUEST: "UPDATE_CUSTOMER_ORDER_REQUEST",
    UPDATE_CUSTOMER_ORDER_SUCCESS: "UPDATE_CUSTOMER_ORDER_SUCCESS",
    UPDATE_CUSTOMER_ORDER_FAILURE: "UPDATE_CUSTOMER_ORDER_FAILURE",
};

export const sellerPostConsts = {
    SELLER_POST_FETCH_REQUEST: 'SELLER_POST_FETCH_REQUEST',
    SELLER_POST_FETCH_SUCCESS: 'SELLER_POST_FETCH_SUCCESS',
    SELLER_POST_FETCH_FAILED: 'SELLER_POST_FETCH_FAILED',
    SELLER_POST_STATUS_UPDATE_REQUEST: 'SELLER_POST_STATUS_UPDATE_REQUEST',
    SELLER_POST_STATUS_UPDATE_SUCCESS: 'SELLER_POST_STATUS_UPDATE_SUCCESS',
    SELLER_POST_STATUS_UPDATE_FAILED: 'SELLER_POST_STATUS_UPDATE_FAILED',
    SELLER_POST_DELETE_REQUEST: 'SELLER_POST_DELETE_REQUEST',
    SELLER_POST_DELETE_SUCCESS: 'SELLER_POST_DELETE_SUCCESS',
    SELLER_POST_DELETE_FAILED: 'SELLER_POST_DELETE_FAILED',
}

export const buyerPostConsts = {
    BUYER_POST_FETCH_REQUEST: 'BUYER_POST_FETCH_REQUEST',
    BUYER_POST_FETCH_SUCCESS: 'BUYER_POST_FETCH_SUCCESS',
    BUYER_POST_FETCH_FAILED: 'BUYER_POST_FETCH_FAILED',
    BUYER_POST_STATUS_UPDATE_REQUEST: 'BUYER_POST_STATUS_UPDATE_REQUEST',
    BUYER_POST_STATUS_UPDATE_SUCCESS: 'BUYER_POST_STATUS_UPDATE_SUCCESS',
    BUYER_POST_STATUS_UPDATE_FAILED: 'BUYER_POST_STATUS_UPDATE_FAILED',
    BUYER_POST_DELETE_REQUEST: 'BUYER_POST_DELETE_REQUEST',
    BUYER_POST_DELETE_SUCCESS: 'BUYER_POST_DELETE_SUCCESS',
    BUYER_POST_DELETE_FAILED: 'BUYER_POST_DELETE_FAILED',
}