export const sellerPostConsts = {
    SELLER_POST_FETCH_REQUEST: 'SELLER_POST_FETCH_REQUEST',
    SELLER_POST_FETCH_SUCCESS: 'SELLER_POST_FETCH_SUCCESS',
    SELLER_POST_FETCH_FAILED: 'SELLER_POST_FETCH_FAILED'
}

export const buyerPostConsts = {
    BUYER_POST_FETCH_REQUEST: 'BUYER_POST_FETCH_REQUEST',
    BUYER_POST_FETCH_SUCCESS: 'BUYER_POST_FETCH_SUCCESS',
    BUYER_POST_FETCH_FAILED: 'BUYER_POST_FETCH_FAILED'
}

export const catConsts = {
    CATEGORY_FETCH_REQUEST: 'CATEGORY_FETCH_REQUEST',
    CATEGORY_FETCH_SUCCESS: 'CATEGORY_FETCH_SUCCESS',
    CATEGORY_FETCH_FAILED: 'CATEGORY_FETCH_FAILED',
}